// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IdentityMsg.proto

package org.remoteandroid.internal;

public final class IdentityMsg {
  private IdentityMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IdentityOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string uuid = 10;
    boolean hasUuid();
    String getUuid();
    
    // optional string name = 11;
    boolean hasName();
    String getName();
    
    // optional bytes publicKey = 12;
    boolean hasPublicKey();
    com.google.protobuf.ByteString getPublicKey();
    
    // optional int32 version = 13;
    boolean hasVersion();
    int getVersion();
    
    // optional string os = 14;
    boolean hasOs();
    String getOs();
    
    // optional int32 capability = 15;
    boolean hasCapability();
    int getCapability();
    
    // optional bool bounded = 16;
    boolean hasBounded();
    boolean getBounded();
    
    // optional string ethernetMac = 20;
    boolean hasEthernetMac();
    String getEthernetMac();
    
    // optional int32 bluetoothAnonymous = 30;
    boolean hasBluetoothAnonymous();
    int getBluetoothAnonymous();
    
    // optional string bluetoothId = 31;
    boolean hasBluetoothId();
    String getBluetoothId();
  }
  public static final class Identity extends
      com.google.protobuf.GeneratedMessageLite
      implements IdentityOrBuilder {
    // Use Identity.newBuilder() to construct.
    private Identity(Builder builder) {
      super(builder);
    }
    private Identity(boolean noInit) {}
    
    private static final Identity defaultInstance;
    public static Identity getDefaultInstance() {
      return defaultInstance;
    }
    
    public Identity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string uuid = 10;
    public static final int UUID_FIELD_NUMBER = 10;
    private java.lang.Object uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 11;
    public static final int NAME_FIELD_NUMBER = 11;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes publicKey = 12;
    public static final int PUBLICKEY_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString publicKey_;
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    
    // optional int32 version = 13;
    public static final int VERSION_FIELD_NUMBER = 13;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getVersion() {
      return version_;
    }
    
    // optional string os = 14;
    public static final int OS_FIELD_NUMBER = 14;
    private java.lang.Object os_;
    public boolean hasOs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getOs() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          os_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 capability = 15;
    public static final int CAPABILITY_FIELD_NUMBER = 15;
    private int capability_;
    public boolean hasCapability() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCapability() {
      return capability_;
    }
    
    // optional bool bounded = 16;
    public static final int BOUNDED_FIELD_NUMBER = 16;
    private boolean bounded_;
    public boolean hasBounded() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getBounded() {
      return bounded_;
    }
    
    // optional string ethernetMac = 20;
    public static final int ETHERNETMAC_FIELD_NUMBER = 20;
    private java.lang.Object ethernetMac_;
    public boolean hasEthernetMac() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getEthernetMac() {
      java.lang.Object ref = ethernetMac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ethernetMac_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEthernetMacBytes() {
      java.lang.Object ref = ethernetMac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ethernetMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 bluetoothAnonymous = 30;
    public static final int BLUETOOTHANONYMOUS_FIELD_NUMBER = 30;
    private int bluetoothAnonymous_;
    public boolean hasBluetoothAnonymous() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getBluetoothAnonymous() {
      return bluetoothAnonymous_;
    }
    
    // optional string bluetoothId = 31;
    public static final int BLUETOOTHID_FIELD_NUMBER = 31;
    private java.lang.Object bluetoothId_;
    public boolean hasBluetoothId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getBluetoothId() {
      java.lang.Object ref = bluetoothId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bluetoothId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBluetoothIdBytes() {
      java.lang.Object ref = bluetoothId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bluetoothId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uuid_ = "";
      name_ = "";
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      version_ = 0;
      os_ = "";
      capability_ = 0;
      bounded_ = false;
      ethernetMac_ = "";
      bluetoothAnonymous_ = 0;
      bluetoothId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(10, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(11, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(12, publicKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(13, version_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(14, getOsBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(15, capability_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(16, bounded_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(20, getEthernetMacBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(30, bluetoothAnonymous_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(31, getBluetoothIdBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, publicKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, version_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getOsBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, capability_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, bounded_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getEthernetMacBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(30, bluetoothAnonymous_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(31, getBluetoothIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.IdentityMsg.Identity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.remoteandroid.internal.IdentityMsg.Identity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.remoteandroid.internal.IdentityMsg.Identity, Builder>
        implements org.remoteandroid.internal.IdentityMsg.IdentityOrBuilder {
      // Construct using org.remoteandroid.lib.IdentityMsg.Identity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        os_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        capability_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        bounded_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        ethernetMac_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        bluetoothAnonymous_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        bluetoothId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.remoteandroid.internal.IdentityMsg.Identity getDefaultInstanceForType() {
        return org.remoteandroid.internal.IdentityMsg.Identity.getDefaultInstance();
      }
      
      public org.remoteandroid.internal.IdentityMsg.Identity build() {
        org.remoteandroid.internal.IdentityMsg.Identity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.remoteandroid.internal.IdentityMsg.Identity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.remoteandroid.internal.IdentityMsg.Identity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.remoteandroid.internal.IdentityMsg.Identity buildPartial() {
        org.remoteandroid.internal.IdentityMsg.Identity result = new org.remoteandroid.internal.IdentityMsg.Identity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.capability_ = capability_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bounded_ = bounded_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ethernetMac_ = ethernetMac_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.bluetoothAnonymous_ = bluetoothAnonymous_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.bluetoothId_ = bluetoothId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.remoteandroid.internal.IdentityMsg.Identity other) {
        if (other == org.remoteandroid.internal.IdentityMsg.Identity.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasOs()) {
          setOs(other.getOs());
        }
        if (other.hasCapability()) {
          setCapability(other.getCapability());
        }
        if (other.hasBounded()) {
          setBounded(other.getBounded());
        }
        if (other.hasEthernetMac()) {
          setEthernetMac(other.getEthernetMac());
        }
        if (other.hasBluetoothAnonymous()) {
          setBluetoothAnonymous(other.getBluetoothAnonymous());
        }
        if (other.hasBluetoothId()) {
          setBluetoothId(other.getBluetoothId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 82: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000004;
              publicKey_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000008;
              version_ = input.readInt32();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000010;
              os_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000020;
              capability_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00000040;
              bounded_ = input.readBool();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000080;
              ethernetMac_ = input.readBytes();
              break;
            }
            case 240: {
              bitField0_ |= 0x00000100;
              bluetoothAnonymous_ = input.readInt32();
              break;
            }
            case 250: {
              bitField0_ |= 0x00000200;
              bluetoothId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string uuid = 10;
      private java.lang.Object uuid_ = "";
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        
        return this;
      }
      void setUuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uuid_ = value;
        
      }
      
      // optional string name = 11;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        
      }
      
      // optional bytes publicKey = 12;
      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        publicKey_ = value;
        
        return this;
      }
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        publicKey_ = getDefaultInstance().getPublicKey();
        
        return this;
      }
      
      // optional int32 version = 13;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000008;
        version_ = value;
        
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        
        return this;
      }
      
      // optional string os = 14;
      private java.lang.Object os_ = "";
      public boolean hasOs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getOs() {
        java.lang.Object ref = os_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          os_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        os_ = value;
        
        return this;
      }
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        os_ = getDefaultInstance().getOs();
        
        return this;
      }
      void setOs(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        os_ = value;
        
      }
      
      // optional int32 capability = 15;
      private int capability_ ;
      public boolean hasCapability() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCapability() {
        return capability_;
      }
      public Builder setCapability(int value) {
        bitField0_ |= 0x00000020;
        capability_ = value;
        
        return this;
      }
      public Builder clearCapability() {
        bitField0_ = (bitField0_ & ~0x00000020);
        capability_ = 0;
        
        return this;
      }
      
      // optional bool bounded = 16;
      private boolean bounded_ ;
      public boolean hasBounded() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getBounded() {
        return bounded_;
      }
      public Builder setBounded(boolean value) {
        bitField0_ |= 0x00000040;
        bounded_ = value;
        
        return this;
      }
      public Builder clearBounded() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bounded_ = false;
        
        return this;
      }
      
      // optional string ethernetMac = 20;
      private java.lang.Object ethernetMac_ = "";
      public boolean hasEthernetMac() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getEthernetMac() {
        java.lang.Object ref = ethernetMac_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ethernetMac_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEthernetMac(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ethernetMac_ = value;
        
        return this;
      }
      public Builder clearEthernetMac() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ethernetMac_ = getDefaultInstance().getEthernetMac();
        
        return this;
      }
      void setEthernetMac(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        ethernetMac_ = value;
        
      }
      
      // optional int32 bluetoothAnonymous = 30;
      private int bluetoothAnonymous_ ;
      public boolean hasBluetoothAnonymous() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getBluetoothAnonymous() {
        return bluetoothAnonymous_;
      }
      public Builder setBluetoothAnonymous(int value) {
        bitField0_ |= 0x00000100;
        bluetoothAnonymous_ = value;
        
        return this;
      }
      public Builder clearBluetoothAnonymous() {
        bitField0_ = (bitField0_ & ~0x00000100);
        bluetoothAnonymous_ = 0;
        
        return this;
      }
      
      // optional string bluetoothId = 31;
      private java.lang.Object bluetoothId_ = "";
      public boolean hasBluetoothId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getBluetoothId() {
        java.lang.Object ref = bluetoothId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bluetoothId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBluetoothId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        bluetoothId_ = value;
        
        return this;
      }
      public Builder clearBluetoothId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        bluetoothId_ = getDefaultInstance().getBluetoothId();
        
        return this;
      }
      void setBluetoothId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        bluetoothId_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:org.remoteandroid.lib.Identity)
    }
    
    static {
      defaultInstance = new Identity(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.remoteandroid.lib.Identity)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
