// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.remoteandroid.internal;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum Type
      implements com.google.protobuf.Internal.EnumLite {
    PING(0, 0),
    CONNECT(1, 10),
    CONNECT_FOR_DISCOVERING(2, 11),
    CONNECT_FOR_COOKIE(3, 12),
    CONNECT_FOR_PAIRING(4, 13),
    PAIRING_CHALENGE(5, 20),
    TRANSACT_RemoteAndroid(6, 40),
    TRANSACT_Binder(7, 41),
    TRANSACT_Apk(8, 42),
    ;
    
    public static final int PING_VALUE = 0;
    public static final int CONNECT_VALUE = 10;
    public static final int CONNECT_FOR_DISCOVERING_VALUE = 11;
    public static final int CONNECT_FOR_COOKIE_VALUE = 12;
    public static final int CONNECT_FOR_PAIRING_VALUE = 13;
    public static final int PAIRING_CHALENGE_VALUE = 20;
    public static final int TRANSACT_RemoteAndroid_VALUE = 40;
    public static final int TRANSACT_Binder_VALUE = 41;
    public static final int TRANSACT_Apk_VALUE = 42;
    
    
    public final int getNumber() { return value; }
    
    public static Type valueOf(int value) {
      switch (value) {
        case 0: return PING;
        case 10: return CONNECT;
        case 11: return CONNECT_FOR_DISCOVERING;
        case 12: return CONNECT_FOR_COOKIE;
        case 13: return CONNECT_FOR_PAIRING;
        case 20: return PAIRING_CHALENGE;
        case 40: return TRANSACT_RemoteAndroid;
        case 41: return TRANSACT_Binder;
        case 42: return TRANSACT_Apk;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };
    
    private final int value;
    
    private Type(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.remoteandroid.internal.Type)
  }
  
  public interface IdentityOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string uuid = 10;
    boolean hasUuid();
    String getUuid();
    
    // optional string name = 11;
    boolean hasName();
    String getName();
    
    // optional bytes publicKey = 12;
    boolean hasPublicKey();
    com.google.protobuf.ByteString getPublicKey();
    
    // optional int32 version = 13;
    boolean hasVersion();
    int getVersion();
    
    // optional string os = 14;
    boolean hasOs();
    String getOs();
    
    // optional int32 capability = 15;
    boolean hasCapability();
    int getCapability();
    
    // optional bool bounded = 16;
    boolean hasBounded();
    boolean getBounded();
    
    // optional string ethernetMac = 20;
    boolean hasEthernetMac();
    String getEthernetMac();
    
    // optional int32 bluetoothAnonymous = 30;
    boolean hasBluetoothAnonymous();
    int getBluetoothAnonymous();
    
    // optional string bluetoothId = 31;
    boolean hasBluetoothId();
    String getBluetoothId();
  }
  public static final class Identity extends
      com.google.protobuf.GeneratedMessageLite
      implements IdentityOrBuilder {
    // Use Identity.newBuilder() to construct.
    private Identity(Builder builder) {
      super(builder);
    }
    private Identity(boolean noInit) {}
    
    private static final Identity defaultInstance;
    public static Identity getDefaultInstance() {
      return defaultInstance;
    }
    
    public Identity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string uuid = 10;
    public static final int UUID_FIELD_NUMBER = 10;
    private java.lang.Object uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 11;
    public static final int NAME_FIELD_NUMBER = 11;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes publicKey = 12;
    public static final int PUBLICKEY_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString publicKey_;
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    
    // optional int32 version = 13;
    public static final int VERSION_FIELD_NUMBER = 13;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getVersion() {
      return version_;
    }
    
    // optional string os = 14;
    public static final int OS_FIELD_NUMBER = 14;
    private java.lang.Object os_;
    public boolean hasOs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getOs() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          os_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 capability = 15;
    public static final int CAPABILITY_FIELD_NUMBER = 15;
    private int capability_;
    public boolean hasCapability() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCapability() {
      return capability_;
    }
    
    // optional bool bounded = 16;
    public static final int BOUNDED_FIELD_NUMBER = 16;
    private boolean bounded_;
    public boolean hasBounded() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getBounded() {
      return bounded_;
    }
    
    // optional string ethernetMac = 20;
    public static final int ETHERNETMAC_FIELD_NUMBER = 20;
    private java.lang.Object ethernetMac_;
    public boolean hasEthernetMac() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getEthernetMac() {
      java.lang.Object ref = ethernetMac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ethernetMac_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEthernetMacBytes() {
      java.lang.Object ref = ethernetMac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ethernetMac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 bluetoothAnonymous = 30;
    public static final int BLUETOOTHANONYMOUS_FIELD_NUMBER = 30;
    private int bluetoothAnonymous_;
    public boolean hasBluetoothAnonymous() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getBluetoothAnonymous() {
      return bluetoothAnonymous_;
    }
    
    // optional string bluetoothId = 31;
    public static final int BLUETOOTHID_FIELD_NUMBER = 31;
    private java.lang.Object bluetoothId_;
    public boolean hasBluetoothId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getBluetoothId() {
      java.lang.Object ref = bluetoothId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          bluetoothId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBluetoothIdBytes() {
      java.lang.Object ref = bluetoothId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        bluetoothId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uuid_ = "";
      name_ = "";
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      version_ = 0;
      os_ = "";
      capability_ = 0;
      bounded_ = false;
      ethernetMac_ = "";
      bluetoothAnonymous_ = 0;
      bluetoothId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(10, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(11, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(12, publicKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(13, version_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(14, getOsBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(15, capability_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(16, bounded_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(20, getEthernetMacBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(30, bluetoothAnonymous_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(31, getBluetoothIdBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, publicKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, version_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getOsBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, capability_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, bounded_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getEthernetMacBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(30, bluetoothAnonymous_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(31, getBluetoothIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.remoteandroid.internal.Messages.Identity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.Messages.Identity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Identity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.remoteandroid.internal.Messages.Identity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.remoteandroid.internal.Messages.Identity, Builder>
        implements org.remoteandroid.internal.Messages.IdentityOrBuilder {
      // Construct using org.remoteandroid.internal.Messages.Identity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        os_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        capability_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        bounded_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        ethernetMac_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        bluetoothAnonymous_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        bluetoothId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.remoteandroid.internal.Messages.Identity getDefaultInstanceForType() {
        return org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
      }
      
      public org.remoteandroid.internal.Messages.Identity build() {
        org.remoteandroid.internal.Messages.Identity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.remoteandroid.internal.Messages.Identity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.remoteandroid.internal.Messages.Identity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.remoteandroid.internal.Messages.Identity buildPartial() {
        org.remoteandroid.internal.Messages.Identity result = new org.remoteandroid.internal.Messages.Identity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.os_ = os_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.capability_ = capability_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bounded_ = bounded_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ethernetMac_ = ethernetMac_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.bluetoothAnonymous_ = bluetoothAnonymous_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.bluetoothId_ = bluetoothId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.remoteandroid.internal.Messages.Identity other) {
        if (other == org.remoteandroid.internal.Messages.Identity.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasOs()) {
          setOs(other.getOs());
        }
        if (other.hasCapability()) {
          setCapability(other.getCapability());
        }
        if (other.hasBounded()) {
          setBounded(other.getBounded());
        }
        if (other.hasEthernetMac()) {
          setEthernetMac(other.getEthernetMac());
        }
        if (other.hasBluetoothAnonymous()) {
          setBluetoothAnonymous(other.getBluetoothAnonymous());
        }
        if (other.hasBluetoothId()) {
          setBluetoothId(other.getBluetoothId());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 82: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000004;
              publicKey_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000008;
              version_ = input.readInt32();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000010;
              os_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000020;
              capability_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00000040;
              bounded_ = input.readBool();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000080;
              ethernetMac_ = input.readBytes();
              break;
            }
            case 240: {
              bitField0_ |= 0x00000100;
              bluetoothAnonymous_ = input.readInt32();
              break;
            }
            case 250: {
              bitField0_ |= 0x00000200;
              bluetoothId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string uuid = 10;
      private java.lang.Object uuid_ = "";
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        
        return this;
      }
      void setUuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uuid_ = value;
        
      }
      
      // optional string name = 11;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        
      }
      
      // optional bytes publicKey = 12;
      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        publicKey_ = value;
        
        return this;
      }
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        publicKey_ = getDefaultInstance().getPublicKey();
        
        return this;
      }
      
      // optional int32 version = 13;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000008;
        version_ = value;
        
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        
        return this;
      }
      
      // optional string os = 14;
      private java.lang.Object os_ = "";
      public boolean hasOs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getOs() {
        java.lang.Object ref = os_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          os_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        os_ = value;
        
        return this;
      }
      public Builder clearOs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        os_ = getDefaultInstance().getOs();
        
        return this;
      }
      void setOs(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        os_ = value;
        
      }
      
      // optional int32 capability = 15;
      private int capability_ ;
      public boolean hasCapability() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCapability() {
        return capability_;
      }
      public Builder setCapability(int value) {
        bitField0_ |= 0x00000020;
        capability_ = value;
        
        return this;
      }
      public Builder clearCapability() {
        bitField0_ = (bitField0_ & ~0x00000020);
        capability_ = 0;
        
        return this;
      }
      
      // optional bool bounded = 16;
      private boolean bounded_ ;
      public boolean hasBounded() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getBounded() {
        return bounded_;
      }
      public Builder setBounded(boolean value) {
        bitField0_ |= 0x00000040;
        bounded_ = value;
        
        return this;
      }
      public Builder clearBounded() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bounded_ = false;
        
        return this;
      }
      
      // optional string ethernetMac = 20;
      private java.lang.Object ethernetMac_ = "";
      public boolean hasEthernetMac() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getEthernetMac() {
        java.lang.Object ref = ethernetMac_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ethernetMac_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEthernetMac(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ethernetMac_ = value;
        
        return this;
      }
      public Builder clearEthernetMac() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ethernetMac_ = getDefaultInstance().getEthernetMac();
        
        return this;
      }
      void setEthernetMac(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        ethernetMac_ = value;
        
      }
      
      // optional int32 bluetoothAnonymous = 30;
      private int bluetoothAnonymous_ ;
      public boolean hasBluetoothAnonymous() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getBluetoothAnonymous() {
        return bluetoothAnonymous_;
      }
      public Builder setBluetoothAnonymous(int value) {
        bitField0_ |= 0x00000100;
        bluetoothAnonymous_ = value;
        
        return this;
      }
      public Builder clearBluetoothAnonymous() {
        bitField0_ = (bitField0_ & ~0x00000100);
        bluetoothAnonymous_ = 0;
        
        return this;
      }
      
      // optional string bluetoothId = 31;
      private java.lang.Object bluetoothId_ = "";
      public boolean hasBluetoothId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getBluetoothId() {
        java.lang.Object ref = bluetoothId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          bluetoothId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBluetoothId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        bluetoothId_ = value;
        
        return this;
      }
      public Builder clearBluetoothId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        bluetoothId_ = getDefaultInstance().getBluetoothId();
        
        return this;
      }
      void setBluetoothId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        bluetoothId_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:org.remoteandroid.internal.Identity)
    }
    
    static {
      defaultInstance = new Identity(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.remoteandroid.internal.Identity)
  }
  
  public interface BroadcastMsgOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .org.remoteandroid.internal.BroadcastMsg.Type type = 1;
    boolean hasType();
    org.remoteandroid.internal.Messages.BroadcastMsg.Type getType();
    
    // required int32 flags = 2;
    boolean hasFlags();
    int getFlags();
    
    // optional .org.remoteandroid.internal.Identity identity = 3;
    boolean hasIdentity();
    org.remoteandroid.internal.Messages.Identity getIdentity();
  }
  public static final class BroadcastMsg extends
      com.google.protobuf.GeneratedMessageLite
      implements BroadcastMsgOrBuilder {
    // Use BroadcastMsg.newBuilder() to construct.
    private BroadcastMsg(Builder builder) {
      super(builder);
    }
    private BroadcastMsg(boolean noInit) {}
    
    private static final BroadcastMsg defaultInstance;
    public static BroadcastMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public BroadcastMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      REQUEST(0, 0),
      RESPONSE(1, 1),
      ;
      
      public static final int REQUEST_VALUE = 0;
      public static final int RESPONSE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      private final int value;
      
      private Type(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:org.remoteandroid.internal.BroadcastMsg.Type)
    }
    
    private int bitField0_;
    // required .org.remoteandroid.internal.BroadcastMsg.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.remoteandroid.internal.Messages.BroadcastMsg.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.remoteandroid.internal.Messages.BroadcastMsg.Type getType() {
      return type_;
    }
    
    // required int32 flags = 2;
    public static final int FLAGS_FIELD_NUMBER = 2;
    private int flags_;
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getFlags() {
      return flags_;
    }
    
    // optional .org.remoteandroid.internal.Identity identity = 3;
    public static final int IDENTITY_FIELD_NUMBER = 3;
    private org.remoteandroid.internal.Messages.Identity identity_;
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.remoteandroid.internal.Messages.Identity getIdentity() {
      return identity_;
    }
    
    private void initFields() {
      type_ = org.remoteandroid.internal.Messages.BroadcastMsg.Type.REQUEST;
      flags_ = 0;
      identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlags()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, flags_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, identity_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flags_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, identity_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.BroadcastMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.remoteandroid.internal.Messages.BroadcastMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.remoteandroid.internal.Messages.BroadcastMsg, Builder>
        implements org.remoteandroid.internal.Messages.BroadcastMsgOrBuilder {
      // Construct using org.remoteandroid.internal.Messages.BroadcastMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = org.remoteandroid.internal.Messages.BroadcastMsg.Type.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.remoteandroid.internal.Messages.BroadcastMsg getDefaultInstanceForType() {
        return org.remoteandroid.internal.Messages.BroadcastMsg.getDefaultInstance();
      }
      
      public org.remoteandroid.internal.Messages.BroadcastMsg build() {
        org.remoteandroid.internal.Messages.BroadcastMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.remoteandroid.internal.Messages.BroadcastMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.remoteandroid.internal.Messages.BroadcastMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.remoteandroid.internal.Messages.BroadcastMsg buildPartial() {
        org.remoteandroid.internal.Messages.BroadcastMsg result = new org.remoteandroid.internal.Messages.BroadcastMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.identity_ = identity_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.remoteandroid.internal.Messages.BroadcastMsg other) {
        if (other == org.remoteandroid.internal.Messages.BroadcastMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasIdentity()) {
          mergeIdentity(other.getIdentity());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasFlags()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.remoteandroid.internal.Messages.BroadcastMsg.Type value = org.remoteandroid.internal.Messages.BroadcastMsg.Type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              flags_ = input.readInt32();
              break;
            }
            case 26: {
              org.remoteandroid.internal.Messages.Identity.Builder subBuilder = org.remoteandroid.internal.Messages.Identity.newBuilder();
              if (hasIdentity()) {
                subBuilder.mergeFrom(getIdentity());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIdentity(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.remoteandroid.internal.BroadcastMsg.Type type = 1;
      private org.remoteandroid.internal.Messages.BroadcastMsg.Type type_ = org.remoteandroid.internal.Messages.BroadcastMsg.Type.REQUEST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.remoteandroid.internal.Messages.BroadcastMsg.Type getType() {
        return type_;
      }
      public Builder setType(org.remoteandroid.internal.Messages.BroadcastMsg.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.remoteandroid.internal.Messages.BroadcastMsg.Type.REQUEST;
        
        return this;
      }
      
      // required int32 flags = 2;
      private int flags_ ;
      public boolean hasFlags() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getFlags() {
        return flags_;
      }
      public Builder setFlags(int value) {
        bitField0_ |= 0x00000002;
        flags_ = value;
        
        return this;
      }
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flags_ = 0;
        
        return this;
      }
      
      // optional .org.remoteandroid.internal.Identity identity = 3;
      private org.remoteandroid.internal.Messages.Identity identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
      public boolean hasIdentity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.remoteandroid.internal.Messages.Identity getIdentity() {
        return identity_;
      }
      public Builder setIdentity(org.remoteandroid.internal.Messages.Identity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        identity_ = value;
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setIdentity(
          org.remoteandroid.internal.Messages.Identity.Builder builderForValue) {
        identity_ = builderForValue.build();
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeIdentity(org.remoteandroid.internal.Messages.Identity value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            identity_ != org.remoteandroid.internal.Messages.Identity.getDefaultInstance()) {
          identity_ =
            org.remoteandroid.internal.Messages.Identity.newBuilder(identity_).mergeFrom(value).buildPartial();
        } else {
          identity_ = value;
        }
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearIdentity() {
        identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.remoteandroid.internal.BroadcastMsg)
    }
    
    static {
      defaultInstance = new BroadcastMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.remoteandroid.internal.BroadcastMsg)
  }
  
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .org.remoteandroid.internal.Type type = 1;
    boolean hasType();
    org.remoteandroid.internal.Messages.Type getType();
    
    // optional int64 threadid = 2;
    boolean hasThreadid();
    long getThreadid();
    
    // optional int64 timeout = 3;
    boolean hasTimeout();
    long getTimeout();
    
    // optional .org.remoteandroid.internal.Identity identity = 10;
    boolean hasIdentity();
    org.remoteandroid.internal.Messages.Identity getIdentity();
    
    // optional bytes publickey = 11;
    boolean hasPublickey();
    com.google.protobuf.ByteString getPublickey();
    
    // optional int64 cookie = 12;
    boolean hasCookie();
    long getCookie();
    
    // optional int32 challengestep = 13;
    boolean hasChallengestep();
    int getChallengestep();
    
    // optional bytes challenge1 = 14;
    boolean hasChallenge1();
    com.google.protobuf.ByteString getChallenge1();
    
    // optional bytes challenge2 = 15;
    boolean hasChallenge2();
    com.google.protobuf.ByteString getChallenge2();
    
    // optional int32 capability = 20;
    boolean hasCapability();
    int getCapability();
    
    // optional int32 pairingstep = 21;
    boolean hasPairingstep();
    int getPairingstep();
    
    // optional int32 status = 40;
    boolean hasStatus();
    int getStatus();
    
    // optional int32 oid = 41;
    boolean hasOid();
    int getOid();
    
    // optional int32 cmd = 42;
    boolean hasCmd();
    int getCmd();
    
    // optional bytes data = 43;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // optional int32 flags = 44;
    boolean hasFlags();
    int getFlags();
    
    // optional bool rc = 45;
    boolean hasRc();
    boolean getRc();
    
    // optional int32 rcInt = 46;
    boolean hasRcInt();
    int getRcInt();
    
    // optional bytes reply = 47;
    boolean hasReply();
    com.google.protobuf.ByteString getReply();
  }
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageLite
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(Builder builder) {
      super(builder);
    }
    private Msg(boolean noInit) {}
    
    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .org.remoteandroid.internal.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.remoteandroid.internal.Messages.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.remoteandroid.internal.Messages.Type getType() {
      return type_;
    }
    
    // optional int64 threadid = 2;
    public static final int THREADID_FIELD_NUMBER = 2;
    private long threadid_;
    public boolean hasThreadid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getThreadid() {
      return threadid_;
    }
    
    // optional int64 timeout = 3;
    public static final int TIMEOUT_FIELD_NUMBER = 3;
    private long timeout_;
    public boolean hasTimeout() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getTimeout() {
      return timeout_;
    }
    
    // optional .org.remoteandroid.internal.Identity identity = 10;
    public static final int IDENTITY_FIELD_NUMBER = 10;
    private org.remoteandroid.internal.Messages.Identity identity_;
    public boolean hasIdentity() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public org.remoteandroid.internal.Messages.Identity getIdentity() {
      return identity_;
    }
    
    // optional bytes publickey = 11;
    public static final int PUBLICKEY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString publickey_;
    public boolean hasPublickey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getPublickey() {
      return publickey_;
    }
    
    // optional int64 cookie = 12;
    public static final int COOKIE_FIELD_NUMBER = 12;
    private long cookie_;
    public boolean hasCookie() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getCookie() {
      return cookie_;
    }
    
    // optional int32 challengestep = 13;
    public static final int CHALLENGESTEP_FIELD_NUMBER = 13;
    private int challengestep_;
    public boolean hasChallengestep() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getChallengestep() {
      return challengestep_;
    }
    
    // optional bytes challenge1 = 14;
    public static final int CHALLENGE1_FIELD_NUMBER = 14;
    private com.google.protobuf.ByteString challenge1_;
    public boolean hasChallenge1() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getChallenge1() {
      return challenge1_;
    }
    
    // optional bytes challenge2 = 15;
    public static final int CHALLENGE2_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString challenge2_;
    public boolean hasChallenge2() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public com.google.protobuf.ByteString getChallenge2() {
      return challenge2_;
    }
    
    // optional int32 capability = 20;
    public static final int CAPABILITY_FIELD_NUMBER = 20;
    private int capability_;
    public boolean hasCapability() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getCapability() {
      return capability_;
    }
    
    // optional int32 pairingstep = 21;
    public static final int PAIRINGSTEP_FIELD_NUMBER = 21;
    private int pairingstep_;
    public boolean hasPairingstep() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getPairingstep() {
      return pairingstep_;
    }
    
    // optional int32 status = 40;
    public static final int STATUS_FIELD_NUMBER = 40;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional int32 oid = 41;
    public static final int OID_FIELD_NUMBER = 41;
    private int oid_;
    public boolean hasOid() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getOid() {
      return oid_;
    }
    
    // optional int32 cmd = 42;
    public static final int CMD_FIELD_NUMBER = 42;
    private int cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getCmd() {
      return cmd_;
    }
    
    // optional bytes data = 43;
    public static final int DATA_FIELD_NUMBER = 43;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // optional int32 flags = 44;
    public static final int FLAGS_FIELD_NUMBER = 44;
    private int flags_;
    public boolean hasFlags() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public int getFlags() {
      return flags_;
    }
    
    // optional bool rc = 45;
    public static final int RC_FIELD_NUMBER = 45;
    private boolean rc_;
    public boolean hasRc() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public boolean getRc() {
      return rc_;
    }
    
    // optional int32 rcInt = 46;
    public static final int RCINT_FIELD_NUMBER = 46;
    private int rcInt_;
    public boolean hasRcInt() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public int getRcInt() {
      return rcInt_;
    }
    
    // optional bytes reply = 47;
    public static final int REPLY_FIELD_NUMBER = 47;
    private com.google.protobuf.ByteString reply_;
    public boolean hasReply() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public com.google.protobuf.ByteString getReply() {
      return reply_;
    }
    
    private void initFields() {
      type_ = org.remoteandroid.internal.Messages.Type.PING;
      threadid_ = 0L;
      timeout_ = 0L;
      identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
      publickey_ = com.google.protobuf.ByteString.EMPTY;
      cookie_ = 0L;
      challengestep_ = 0;
      challenge1_ = com.google.protobuf.ByteString.EMPTY;
      challenge2_ = com.google.protobuf.ByteString.EMPTY;
      capability_ = 0;
      pairingstep_ = 0;
      status_ = 0;
      oid_ = 0;
      cmd_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      flags_ = 0;
      rc_ = false;
      rcInt_ = 0;
      reply_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, threadid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeout_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(10, identity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(11, publickey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(12, cookie_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(13, challengestep_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(14, challenge1_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(15, challenge2_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(20, capability_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(21, pairingstep_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(40, status_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(41, oid_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(42, cmd_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(43, data_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(44, flags_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBool(45, rc_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt32(46, rcInt_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeBytes(47, reply_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, threadid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeout_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, identity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, publickey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, cookie_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, challengestep_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, challenge1_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, challenge2_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, capability_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, pairingstep_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(40, status_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(41, oid_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(42, cmd_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(43, data_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(44, flags_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(45, rc_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(46, rcInt_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(47, reply_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.remoteandroid.internal.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.Messages.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.internal.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.remoteandroid.internal.Messages.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.remoteandroid.internal.Messages.Msg, Builder>
        implements org.remoteandroid.internal.Messages.MsgOrBuilder {
      // Construct using org.remoteandroid.internal.Messages.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = org.remoteandroid.internal.Messages.Type.PING;
        bitField0_ = (bitField0_ & ~0x00000001);
        threadid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeout_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        publickey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        cookie_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        challengestep_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        challenge1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        challenge2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        capability_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        pairingstep_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        oid_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00004000);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        rc_ = false;
        bitField0_ = (bitField0_ & ~0x00010000);
        rcInt_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        reply_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00040000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.remoteandroid.internal.Messages.Msg getDefaultInstanceForType() {
        return org.remoteandroid.internal.Messages.Msg.getDefaultInstance();
      }
      
      public org.remoteandroid.internal.Messages.Msg build() {
        org.remoteandroid.internal.Messages.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.remoteandroid.internal.Messages.Msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.remoteandroid.internal.Messages.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.remoteandroid.internal.Messages.Msg buildPartial() {
        org.remoteandroid.internal.Messages.Msg result = new org.remoteandroid.internal.Messages.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.threadid_ = threadid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeout_ = timeout_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.identity_ = identity_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.publickey_ = publickey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.cookie_ = cookie_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.challengestep_ = challengestep_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.challenge1_ = challenge1_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.challenge2_ = challenge2_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.capability_ = capability_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.pairingstep_ = pairingstep_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.oid_ = oid_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.rc_ = rc_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.rcInt_ = rcInt_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.reply_ = reply_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.remoteandroid.internal.Messages.Msg other) {
        if (other == org.remoteandroid.internal.Messages.Msg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasThreadid()) {
          setThreadid(other.getThreadid());
        }
        if (other.hasTimeout()) {
          setTimeout(other.getTimeout());
        }
        if (other.hasIdentity()) {
          mergeIdentity(other.getIdentity());
        }
        if (other.hasPublickey()) {
          setPublickey(other.getPublickey());
        }
        if (other.hasCookie()) {
          setCookie(other.getCookie());
        }
        if (other.hasChallengestep()) {
          setChallengestep(other.getChallengestep());
        }
        if (other.hasChallenge1()) {
          setChallenge1(other.getChallenge1());
        }
        if (other.hasChallenge2()) {
          setChallenge2(other.getChallenge2());
        }
        if (other.hasCapability()) {
          setCapability(other.getCapability());
        }
        if (other.hasPairingstep()) {
          setPairingstep(other.getPairingstep());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasOid()) {
          setOid(other.getOid());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasRc()) {
          setRc(other.getRc());
        }
        if (other.hasRcInt()) {
          setRcInt(other.getRcInt());
        }
        if (other.hasReply()) {
          setReply(other.getReply());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.remoteandroid.internal.Messages.Type value = org.remoteandroid.internal.Messages.Type.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              threadid_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeout_ = input.readInt64();
              break;
            }
            case 82: {
              org.remoteandroid.internal.Messages.Identity.Builder subBuilder = org.remoteandroid.internal.Messages.Identity.newBuilder();
              if (hasIdentity()) {
                subBuilder.mergeFrom(getIdentity());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIdentity(subBuilder.buildPartial());
              break;
            }
            case 90: {
              bitField0_ |= 0x00000010;
              publickey_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000020;
              cookie_ = input.readInt64();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000040;
              challengestep_ = input.readInt32();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000080;
              challenge1_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00000100;
              challenge2_ = input.readBytes();
              break;
            }
            case 160: {
              bitField0_ |= 0x00000200;
              capability_ = input.readInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00000400;
              pairingstep_ = input.readInt32();
              break;
            }
            case 320: {
              bitField0_ |= 0x00000800;
              status_ = input.readInt32();
              break;
            }
            case 328: {
              bitField0_ |= 0x00001000;
              oid_ = input.readInt32();
              break;
            }
            case 336: {
              bitField0_ |= 0x00002000;
              cmd_ = input.readInt32();
              break;
            }
            case 346: {
              bitField0_ |= 0x00004000;
              data_ = input.readBytes();
              break;
            }
            case 352: {
              bitField0_ |= 0x00008000;
              flags_ = input.readInt32();
              break;
            }
            case 360: {
              bitField0_ |= 0x00010000;
              rc_ = input.readBool();
              break;
            }
            case 368: {
              bitField0_ |= 0x00020000;
              rcInt_ = input.readInt32();
              break;
            }
            case 378: {
              bitField0_ |= 0x00040000;
              reply_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.remoteandroid.internal.Type type = 1;
      private org.remoteandroid.internal.Messages.Type type_ = org.remoteandroid.internal.Messages.Type.PING;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.remoteandroid.internal.Messages.Type getType() {
        return type_;
      }
      public Builder setType(org.remoteandroid.internal.Messages.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.remoteandroid.internal.Messages.Type.PING;
        
        return this;
      }
      
      // optional int64 threadid = 2;
      private long threadid_ ;
      public boolean hasThreadid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getThreadid() {
        return threadid_;
      }
      public Builder setThreadid(long value) {
        bitField0_ |= 0x00000002;
        threadid_ = value;
        
        return this;
      }
      public Builder clearThreadid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        threadid_ = 0L;
        
        return this;
      }
      
      // optional int64 timeout = 3;
      private long timeout_ ;
      public boolean hasTimeout() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTimeout() {
        return timeout_;
      }
      public Builder setTimeout(long value) {
        bitField0_ |= 0x00000004;
        timeout_ = value;
        
        return this;
      }
      public Builder clearTimeout() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeout_ = 0L;
        
        return this;
      }
      
      // optional .org.remoteandroid.internal.Identity identity = 10;
      private org.remoteandroid.internal.Messages.Identity identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
      public boolean hasIdentity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public org.remoteandroid.internal.Messages.Identity getIdentity() {
        return identity_;
      }
      public Builder setIdentity(org.remoteandroid.internal.Messages.Identity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        identity_ = value;
        
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setIdentity(
          org.remoteandroid.internal.Messages.Identity.Builder builderForValue) {
        identity_ = builderForValue.build();
        
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeIdentity(org.remoteandroid.internal.Messages.Identity value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            identity_ != org.remoteandroid.internal.Messages.Identity.getDefaultInstance()) {
          identity_ =
            org.remoteandroid.internal.Messages.Identity.newBuilder(identity_).mergeFrom(value).buildPartial();
        } else {
          identity_ = value;
        }
        
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearIdentity() {
        identity_ = org.remoteandroid.internal.Messages.Identity.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      // optional bytes publickey = 11;
      private com.google.protobuf.ByteString publickey_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPublickey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getPublickey() {
        return publickey_;
      }
      public Builder setPublickey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        publickey_ = value;
        
        return this;
      }
      public Builder clearPublickey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        publickey_ = getDefaultInstance().getPublickey();
        
        return this;
      }
      
      // optional int64 cookie = 12;
      private long cookie_ ;
      public boolean hasCookie() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getCookie() {
        return cookie_;
      }
      public Builder setCookie(long value) {
        bitField0_ |= 0x00000020;
        cookie_ = value;
        
        return this;
      }
      public Builder clearCookie() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cookie_ = 0L;
        
        return this;
      }
      
      // optional int32 challengestep = 13;
      private int challengestep_ ;
      public boolean hasChallengestep() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getChallengestep() {
        return challengestep_;
      }
      public Builder setChallengestep(int value) {
        bitField0_ |= 0x00000040;
        challengestep_ = value;
        
        return this;
      }
      public Builder clearChallengestep() {
        bitField0_ = (bitField0_ & ~0x00000040);
        challengestep_ = 0;
        
        return this;
      }
      
      // optional bytes challenge1 = 14;
      private com.google.protobuf.ByteString challenge1_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasChallenge1() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getChallenge1() {
        return challenge1_;
      }
      public Builder setChallenge1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        challenge1_ = value;
        
        return this;
      }
      public Builder clearChallenge1() {
        bitField0_ = (bitField0_ & ~0x00000080);
        challenge1_ = getDefaultInstance().getChallenge1();
        
        return this;
      }
      
      // optional bytes challenge2 = 15;
      private com.google.protobuf.ByteString challenge2_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasChallenge2() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public com.google.protobuf.ByteString getChallenge2() {
        return challenge2_;
      }
      public Builder setChallenge2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        challenge2_ = value;
        
        return this;
      }
      public Builder clearChallenge2() {
        bitField0_ = (bitField0_ & ~0x00000100);
        challenge2_ = getDefaultInstance().getChallenge2();
        
        return this;
      }
      
      // optional int32 capability = 20;
      private int capability_ ;
      public boolean hasCapability() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getCapability() {
        return capability_;
      }
      public Builder setCapability(int value) {
        bitField0_ |= 0x00000200;
        capability_ = value;
        
        return this;
      }
      public Builder clearCapability() {
        bitField0_ = (bitField0_ & ~0x00000200);
        capability_ = 0;
        
        return this;
      }
      
      // optional int32 pairingstep = 21;
      private int pairingstep_ ;
      public boolean hasPairingstep() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getPairingstep() {
        return pairingstep_;
      }
      public Builder setPairingstep(int value) {
        bitField0_ |= 0x00000400;
        pairingstep_ = value;
        
        return this;
      }
      public Builder clearPairingstep() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pairingstep_ = 0;
        
        return this;
      }
      
      // optional int32 status = 40;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000800;
        status_ = value;
        
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000800);
        status_ = 0;
        
        return this;
      }
      
      // optional int32 oid = 41;
      private int oid_ ;
      public boolean hasOid() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getOid() {
        return oid_;
      }
      public Builder setOid(int value) {
        bitField0_ |= 0x00001000;
        oid_ = value;
        
        return this;
      }
      public Builder clearOid() {
        bitField0_ = (bitField0_ & ~0x00001000);
        oid_ = 0;
        
        return this;
      }
      
      // optional int32 cmd = 42;
      private int cmd_ ;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getCmd() {
        return cmd_;
      }
      public Builder setCmd(int value) {
        bitField0_ |= 0x00002000;
        cmd_ = value;
        
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00002000);
        cmd_ = 0;
        
        return this;
      }
      
      // optional bytes data = 43;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        data_ = value;
        
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00004000);
        data_ = getDefaultInstance().getData();
        
        return this;
      }
      
      // optional int32 flags = 44;
      private int flags_ ;
      public boolean hasFlags() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public int getFlags() {
        return flags_;
      }
      public Builder setFlags(int value) {
        bitField0_ |= 0x00008000;
        flags_ = value;
        
        return this;
      }
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00008000);
        flags_ = 0;
        
        return this;
      }
      
      // optional bool rc = 45;
      private boolean rc_ ;
      public boolean hasRc() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public boolean getRc() {
        return rc_;
      }
      public Builder setRc(boolean value) {
        bitField0_ |= 0x00010000;
        rc_ = value;
        
        return this;
      }
      public Builder clearRc() {
        bitField0_ = (bitField0_ & ~0x00010000);
        rc_ = false;
        
        return this;
      }
      
      // optional int32 rcInt = 46;
      private int rcInt_ ;
      public boolean hasRcInt() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public int getRcInt() {
        return rcInt_;
      }
      public Builder setRcInt(int value) {
        bitField0_ |= 0x00020000;
        rcInt_ = value;
        
        return this;
      }
      public Builder clearRcInt() {
        bitField0_ = (bitField0_ & ~0x00020000);
        rcInt_ = 0;
        
        return this;
      }
      
      // optional bytes reply = 47;
      private com.google.protobuf.ByteString reply_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasReply() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public com.google.protobuf.ByteString getReply() {
        return reply_;
      }
      public Builder setReply(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        reply_ = value;
        
        return this;
      }
      public Builder clearReply() {
        bitField0_ = (bitField0_ & ~0x00040000);
        reply_ = getDefaultInstance().getReply();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.remoteandroid.internal.Msg)
    }
    
    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.remoteandroid.internal.Msg)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
